#ifndef CONFIG_H
#define CONFIG_H

#define TITLE "Snake"

#define FPS 60

#define WINDOW_HEIGHT 600
#define WINDOW_WIDTH 800

#define PADDING 50
#define BOUNDARY_HEIGHT WINDOW_HEIGHT - PADDING * 2
#define BOUNDARY_WIDTH WINDOW_WIDTH - PADDING * 2

#define BLOCK_SIZE 10

#endif